#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [2]:
a = np.linspace(12, 24, 12, endpoint = False, dtype='int32')
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
for i in range(1, len(a) + 1):
    if i>1 and len(a) % i == 0:
        print(a.reshape(i,int(len(a)/i)))

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
for i in range(1, int(len(a)/2) +1):
    if len(a) % i == 0:
        print(a.reshape(i, -1)) if i>1 else print(a.reshape(-1, i))

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [5]:
b = np.array([[12],[13],[14],[15],[16],[17],[18],[19],[20],[21],[22],[23]])
print('a[0]= ',a[0], '\n b[0]= ', b[0])
b.ndim

a[0]=  12 
 b[0]=  [12]


2

Нет - нельзя. Если взять элемент по индексу из одномерного массива а, то получаем - элемент; в случае массива b - получаем одномерный массив.
Атрибут ndim показал, что размерность массива -2.

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
n = np.random.randn(3, 4)
print(n, '\n\n', n.flatten())
np.size(n)

[[-0.90202513 -0.09771029  1.36123202  0.9370488 ]
 [-0.26454406  1.26446865  0.39514688  0.45804742]
 [-0.38835389  1.16042579  0.47845176  1.16840612]] 

 [-0.90202513 -0.09771029  1.36123202  0.9370488  -0.26454406  1.26446865
  0.39514688  0.45804742 -0.38835389  1.16042579  0.47845176  1.16840612]


12

Для такой размерности массива значения не всегда корректны, но при увеличении размерности стандартная функция randn() выдает хорошие результаты.

#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [7]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [8]:
b = a.reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Массив a одномерный, b - двумерный

#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [9]:
a = np.zeros((2,2))
b = np.ones((3,2))
v = np.vstack((a, b))
print(v, '\n size: ', v.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 size:  10


In [10]:
# посути тоже самое, по постановке задачи решила, что может ожидается типа такого решения
x = int((10 -2)/4)
a = np.zeros((x,2))
b = np.ones((x + 1,2))
v = np.vstack((a, b))
print(v, '\n size: ', v.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 size:  10


#### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [11]:
a = np.arange(13)
print(a)
a.resize(4,3)
print(a)
At = a.T
print(At)
B = np.dot(a, At)
B

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [12]:
B.size, B.shape

(16, (4, 4))

In [13]:
 np.linalg.det(B)

0.0

Обратную матрицу для В вычислить не получится, т.к. определитель матрицы В равен 0.

#### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [14]:
np.random.seed(42)
print(np.random.rand(3))
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]


#### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [15]:
c = np.arange(16)
print(c)
np.random.shuffle(c)
c

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([ 0, 10, 15,  1,  8,  5, 11,  3, 14,  7, 13,  2,  9,  6,  4, 12])

#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [16]:
C = c.reshape(int(np.sqrt(c.size)),-1)
C

array([[ 0, 10, 15,  1],
       [ 8,  5, 11,  3],
       [14,  7, 13,  2],
       [ 9,  6,  4, 12]])

In [17]:
D = B + C*10
print('Матрица D \n', D, '\n')
print('Определитель - ', np.linalg.det(D),
     '\nРанг матрицы - ', np.linalg.matrix_rank(D),
     '\nОбратная матрица')
D_inv = np.linalg.inv(D)
D_inv

Матрица D 
 [[  5 114 173  42]
 [ 94 100 196 152]
 [163 156 279 232]
 [122 182 252 422]] 

Определитель -  95676799.99999991 
Ранг матрицы -  4 
Обратная матрица


array([[-0.00462599, -0.02290503,  0.02203209, -0.00340187],
       [ 0.01351362, -0.06701123,  0.0359734 ,  0.00301494],
       [-0.0022229 ,  0.04233294, -0.02225534, -0.00279148],
       [-0.00316336,  0.01024303, -0.00859414,  0.00371982]])

#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [18]:
D_inv = np.where(D_inv > 0, 1, 0)
print(D_inv, '\n\n', B, '\n\n', C)
E = np.where(D_inv, B, C)
E

[[0 0 1 0]
 [1 0 1 1]
 [0 1 0 0]
 [0 1 0 1]] 

 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 

 [[ 0 10 15  1]
 [ 8  5 11  3]
 [14  7 13  2]
 [ 9  6  4 12]]


array([[  0,  10,  23,   1],
       [ 14,   5,  86, 122],
       [ 14,  86,  13,   2],
       [  9, 122,   4, 302]])